# Generated by Django 5.2.15 on 2026-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='soni',
            field=models.PositiveIntegerField(default=0, help_text='Ombordagi miqdor (0 = tugagan)'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='yangi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='mavjud',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='vazni',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
